// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS8MKN-vzLCFLDmGfws7uJg5_I4fJKnqM',
    appId: '1:525482754887:web:2886f69b6402f4718a8262',
    messagingSenderId: '525482754887',
    projectId: 'wardly-24081996',
    authDomain: 'wardly-24081996.firebaseapp.com',
    storageBucket: 'wardly-24081996.firebasestorage.app',
    measurementId: 'G-RVWH5RC0NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeYr3qQ4Mpy8yq7qRM3pt-bY3xC4SWJSg',
    appId: '1:525482754887:android:e1ac72bcc2dcc8bf8a8262',
    messagingSenderId: '525482754887',
    projectId: 'wardly-24081996',
    storageBucket: 'wardly-24081996.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsDq-DyqblvWILn7W3h4YrFLd-27ztodc',
    appId: '1:525482754887:ios:06b2cd4f7c31de578a8262',
    messagingSenderId: '525482754887',
    projectId: 'wardly-24081996',
    storageBucket: 'wardly-24081996.firebasestorage.app',
    iosClientId: '525482754887-ajnml4mjhqdbsl2mk5pvst9i9c2lidg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wardly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsDq-DyqblvWILn7W3h4YrFLd-27ztodc',
    appId: '1:525482754887:ios:06b2cd4f7c31de578a8262',
    messagingSenderId: '525482754887',
    projectId: 'wardly-24081996',
    storageBucket: 'wardly-24081996.firebasestorage.app',
    iosClientId: '525482754887-ajnml4mjhqdbsl2mk5pvst9i9c2lidg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wardly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS8MKN-vzLCFLDmGfws7uJg5_I4fJKnqM',
    appId: '1:525482754887:web:8ca590a9dba450e98a8262',
    messagingSenderId: '525482754887',
    projectId: 'wardly-24081996',
    authDomain: 'wardly-24081996.firebaseapp.com',
    storageBucket: 'wardly-24081996.firebasestorage.app',
    measurementId: 'G-YGKJ09SGYR',
  );
}